function: pneumatic
protocol:
  type: mqtt
  host: 192.168.1.88
  port: 1883
  function: pneumatic


#tcp:
#  host: 192.168.1.88
#  port: 5432
#udp:
#  host: 192.168.1.88
#  port: 7700

Logging:
  level: INFO
  file: mylogfile.log