function: pneumatic
protocol:
  type: mqtt
  host: 127.0.0.1
  port: 1883
  function: pneumatic
  retry_s : 1
  sub_topics : []

logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    default:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: default
      stream: ext://sys.stdout

  root:
    level: INFO
    handlers: [console]